version: '3.8'
services:
    postgres:
        image: postgres:15-alpine
        container_name: my-postgres-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: starter
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    # Your existing Next.js app service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3000'
        environment:
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/starter
        depends_on:
            - postgres
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
